import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ahista Tasya Kamila
 */
public class FrameAplikasi extends javax.swing.JFrame {

    /**
     * Creates new form FrameAplikasi
     */
    
    public FrameAplikasi() {
        initComponents();
   
            
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        HOME = new javax.swing.JButton();
        FOOD = new javax.swing.JButton();
        ORDER = new javax.swing.JButton();
        ABOUT = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        foodpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nasgor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bakso = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mieayam = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ikanbakar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sate = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        orderpanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        idpesan = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        pesanan = new javax.swing.JTextField();
        jumlah = new javax.swing.JComboBox<>();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABELPEMESANAN = new javax.swing.JTable();
        tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menupanel.setBackground(new java.awt.Color(0, 153, 255));
        menupanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HOME.setBackground(new java.awt.Color(255, 255, 51));
        HOME.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        HOME.setText("HOME");
        HOME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });
        menupanel.add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        FOOD.setBackground(new java.awt.Color(255, 255, 51));
        FOOD.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        FOOD.setText("FOOD");
        FOOD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        FOOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOODActionPerformed(evt);
            }
        });
        menupanel.add(FOOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        ORDER.setBackground(new java.awt.Color(255, 255, 51));
        ORDER.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        ORDER.setText("ORDER");
        ORDER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ORDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDERActionPerformed(evt);
            }
        });
        menupanel.add(ORDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 30));

        ABOUT.setBackground(new java.awt.Color(255, 255, 51));
        ABOUT.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        ABOUT.setText("ABOUT");
        ABOUT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ABOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABOUTActionPerformed(evt);
            }
        });
        menupanel.add(ABOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 30));

        logout.setBackground(new java.awt.Color(255, 255, 51));
        logout.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menupanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-delivery-64 (1).png"))); // NOI18N
        menupanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, 70));

        mainpanel.setBackground(new java.awt.Color(255, 255, 51));
        mainpanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Shop_free_icons_designed_by_Nikita_Golubev__1_-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setText("KEDAI MINIO");

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel2)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainpanel.add(homepanel, "card2");

        foodpanel.setBackground(new java.awt.Color(255, 255, 51));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setText("Menu Makanan");

        nasgor.setBackground(new java.awt.Color(255, 255, 255));
        nasgor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Nasgor klothok (2).jpeg"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel10.setText("Nasi Goreng");

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel15.setText("15.000");

        javax.swing.GroupLayout nasgorLayout = new javax.swing.GroupLayout(nasgor);
        nasgor.setLayout(nasgorLayout);
        nasgorLayout.setHorizontalGroup(
            nasgorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nasgorLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(nasgorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nasgorLayout.createSequentialGroup()
                        .addGroup(nasgorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nasgorLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(76, 76, 76))))
        );
        nasgorLayout.setVerticalGroup(
            nasgorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nasgorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bakso.setBackground(new java.awt.Color(255, 255, 255));
        bakso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel11.setText("Bakso Mercon");

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel16.setText("20.000");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Baso pedas jeletot (1).jpeg"))); // NOI18N

        javax.swing.GroupLayout baksoLayout = new javax.swing.GroupLayout(bakso);
        bakso.setLayout(baksoLayout);
        baksoLayout.setHorizontalGroup(
            baksoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baksoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(73, 73, 73))
            .addGroup(baksoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(baksoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        baksoLayout.setVerticalGroup(
            baksoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baksoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(20, 20, 20))
        );

        mieayam.setBackground(new java.awt.Color(255, 255, 255));
        mieayam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Mie Ayam (1).jpeg"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setText("Mie Ayam");

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel17.setText("15.000");

        javax.swing.GroupLayout mieayamLayout = new javax.swing.GroupLayout(mieayam);
        mieayam.setLayout(mieayamLayout);
        mieayamLayout.setHorizontalGroup(
            mieayamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mieayamLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(mieayamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel12))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(mieayamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mieayamLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mieayamLayout.setVerticalGroup(
            mieayamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mieayamLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(19, 19, 19))
            .addGroup(mieayamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mieayamLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ikanbakar.setBackground(new java.awt.Color(255, 255, 255));
        ikanbakar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Resep Ikan Nila Bakar Pedas Manis yang Mantap Bumbunya (1).jpeg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel13.setText("Ikan Bakar");

        jLabel18.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel18.setText("30.000");

        javax.swing.GroupLayout ikanbakarLayout = new javax.swing.GroupLayout(ikanbakar);
        ikanbakar.setLayout(ikanbakarLayout);
        ikanbakarLayout.setHorizontalGroup(
            ikanbakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ikanbakarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(ikanbakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikanbakarLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(16, 16, 16)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(ikanbakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ikanbakarLayout.createSequentialGroup()
                    .addGap(0, 57, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 57, Short.MAX_VALUE)))
        );
        ikanbakarLayout.setVerticalGroup(
            ikanbakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ikanbakarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(22, 22, 22))
            .addGroup(ikanbakarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ikanbakarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        sate.setBackground(new java.awt.Color(255, 255, 255));
        sate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Sate Ayam & Bumbu Kacang _ Resep Koki (1).jpeg"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel14.setText("Sate Ayam");

        jLabel19.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel19.setText("30.000");

        javax.swing.GroupLayout sateLayout = new javax.swing.GroupLayout(sate);
        sate.setLayout(sateLayout);
        sateLayout.setHorizontalGroup(
            sateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sateLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(sateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(sateLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(8, 8, 8))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        sateLayout.setVerticalGroup(
            sateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sateLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout foodpanelLayout = new javax.swing.GroupLayout(foodpanel);
        foodpanel.setLayout(foodpanelLayout);
        foodpanelLayout.setHorizontalGroup(
            foodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodpanelLayout.createSequentialGroup()
                .addGroup(foodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(foodpanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(nasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(mieayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(foodpanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(ikanbakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(sate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(foodpanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel4)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        foodpanelLayout.setVerticalGroup(
            foodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(foodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mieayam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nasgor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(foodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ikanbakar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        mainpanel.add(foodpanel, "card3");

        orderpanel.setBackground(new java.awt.Color(255, 255, 51));

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel20.setText("Id_Pesan");

        jLabel21.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel21.setText("Nama ");

        jLabel22.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel22.setText("Alamat");

        jLabel23.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel23.setText("Pesanan");

        jLabel24.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel24.setText("Jumlah");

        idpesan.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        idpesan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        idpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpesanActionPerformed(evt);
            }
        });

        nama.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        alamat.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        pesanan.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        pesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananActionPerformed(evt);
            }
        });

        jumlah.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        edit.setText("Edit");
        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        TABELPEMESANAN.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        TABELPEMESANAN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO", "ID_PESAN", "NAMA", "ALAMAT", "PESANAN", "JUMLAH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABELPEMESANAN.setToolTipText("");
        TABELPEMESANAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABELPEMESANANMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TABELPEMESANAN);

        tambah.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        tambah.setText("Tambah");
        tambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderpanelLayout = new javax.swing.GroupLayout(orderpanel);
        orderpanel.setLayout(orderpanelLayout);
        orderpanelLayout.setHorizontalGroup(
            orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nama)
                    .addComponent(idpesan)
                    .addComponent(alamat)
                    .addComponent(pesanan)
                    .addComponent(jumlah, 0, 246, Short.MAX_VALUE))
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addComponent(hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(orderpanelLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(121, 121, 121))
            .addGroup(orderpanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        orderpanelLayout.setVerticalGroup(
            orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpanelLayout.createSequentialGroup()
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderpanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(idpesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambah)))
                .addGap(18, 18, 18)
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit))
                .addGap(21, 21, 21)
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(reset))
                .addGap(18, 18, 18)
                .addGroup(orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        mainpanel.add(orderpanel, "card4");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FOODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOODActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        //add panel
        mainpanel.add(foodpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_FOODActionPerformed

    private void idpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpesanActionPerformed

    private void pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesananActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql = "UPDATE tbpesanan SET ID_PESAN= '"+idpesan.getText()+"',NAMA='"+nama.getText()
            +"',ALAMAT = '"+alamat.getText()+"', PESANAN = '"+pesanan.getText()+"',JUMLAH = '"+jumlah.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)Koneksii.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, " pesanan berhasil diubah ");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null," pesanan gagal diubah,"+e.getMessage());
        }
        load_tabel();
        kosong();
       
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        
        try {
            String sql = "delete from tbpesanan where id_pesan ='"+idpesan.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksii.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "data gagal dihapus, "+e.getMessage());
        }
        load_tabel();
        kosong();
       
    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        
    }//GEN-LAST:event_resetActionPerformed

    private void TABELPEMESANANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABELPEMESANANMouseClicked
        // TODO add your handling code here:
        int baris = TABELPEMESANAN.rowAtPoint(evt.getPoint());
        String ID_PESAN = TABELPEMESANAN.getValueAt(baris, 1).toString();
        idpesan.setText(ID_PESAN);
        String NAMA = TABELPEMESANAN.getValueAt(baris, 2).toString();
        nama.setText(NAMA);
        String ALAMAT = TABELPEMESANAN.getValueAt(baris, 3).toString();
        alamat.setText(ALAMAT);
        String PESANAN = TABELPEMESANAN.getValueAt(baris, 4).toString();
        pesanan.setText(PESANAN);
        String JUMLAH = TABELPEMESANAN.getValueAt(baris, 5).toString();
        jumlah.setSelectedItem(JUMLAH);
    }//GEN-LAST:event_TABELPEMESANANMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql = "insert into tbpesanan values('"+idpesan.getText()+"','"+nama.getText()+"','"+alamat.getText()
                    +"','"+pesanan.getText()+"','"+jumlah.getSelectedItem()+"')";
            java.sql.Connection conn = (Connection)Koneksii.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Terimakasih, pesanan anda segera dibuat");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "pemesanan gagal, silahkan memesan ulang" + e.getMessage());
        }
        load_tabel();
        kosong();
       
    }//GEN-LAST:event_tambahActionPerformed

    private void ORDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDERActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        // add panel
        mainpanel.add(orderpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_ORDERActionPerformed

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
        // TODO add your handling code here:
        
        //remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        //add panel
        mainpanel.add(homepanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_HOMEActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar ?","PERINGATAN", dialogBtn);
        
        if(dialogResult==0){
            //true condition
            System.exit(0);
        }else{            
        }        
    }//GEN-LAST:event_logoutActionPerformed

    private void ABOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABOUTActionPerformed
        // TODO add your handling code here:
        new Frametentang().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ABOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABOUT;
    private javax.swing.JButton FOOD;
    private javax.swing.JButton HOME;
    private javax.swing.JButton ORDER;
    private javax.swing.JTable TABELPEMESANAN;
    private javax.swing.JTextField alamat;
    private javax.swing.JPanel bakso;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton edit;
    private javax.swing.JPanel foodpanel;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel homepanel;
    private javax.swing.JTextField idpesan;
    private javax.swing.JPanel ikanbakar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jumlah;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JPanel mieayam;
    private javax.swing.JTextField nama;
    private javax.swing.JPanel nasgor;
    private javax.swing.JPanel orderpanel;
    private javax.swing.JTextField pesanan;
    private javax.swing.JButton reset;
    private javax.swing.JPanel sate;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables

   
    private void load_tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("ID_PESAN");
        model.addColumn("NAMA");
        model.addColumn("ALAMAT");
        model.addColumn("PESANAN");
        model.addColumn("JUMLAH");
        
        try{
            int NO = 1;
            String sql = "Select * from tbpesanan";
            java.sql.Connection conn = (Connection)Koneksii.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()){
                model.addRow(new Object[] {NO++,res.getString("ID_PESAN"), res.getString("NAMA"), res.getString("ALAMAT"), res.getString("PESANAN"), res.getString("JUMLAH")});
            }
            TABELPEMESANAN.setModel(model);
        }catch (Exception e){
            
        }
    }
    private void kosong(){
        idpesan.setText(null);
        nama.setText(null);
        alamat.setText(null);
        pesanan.setText(null);
        jumlah.setSelectedItem(this);
    }
}
